"""empty message

Revision ID: e04cd40cf30e
Revises: 59c2dec8a6c6
Create Date: 2024-04-17 10:15:32.170054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04cd40cf30e'
down_revision = '59c2dec8a6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hockey_event_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hockey_event_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hockey_event_table')
    # ### end Alembic commands ###
